=== FixMyBerlin/fixmy.frontend/src/pages/KatasterKI/scheme/profile-request.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "TransportRating": {
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "type": "number"
        },
        "UserGroup": {
            "enum": [
                "bicycle",
                "car",
                "pedestrian",
                "potentialBicycle"
            ],
            "type": "string"
        }
    },
    "properties": {
        "ageGroup": {
            "enum": [
                0,
                1,
                2,
                3
            ],
            "type": "number"
        },
        "berlinTraffic": {
            "type": "string"
        },
        "bicycleAccident": {
            "enum": [
                0,
                1,
                2,
                3
            ],
            "type": "number"
        },
        "bicycleUse": {
            "enum": [
                0,
                1,
                2,
                3
            ],
            "type": "number"
        },
        "bikeReasons": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "district": {
            "type": "string"
        },
        "gender": {
            "enum": [
                "d",
                "m",
                "w"
            ],
            "type": "string"
        },
        "hasChildren": {
            "type": "boolean"
        },
        "isAgbAccepted": {
            "type": "boolean"
        },
        "transportRatings": {
            "additionalProperties": {
                "$ref": "#/definitions/TransportRating"
            },
            "type": "object"
        },
        "userGroup": {
            "$ref": "#/definitions/UserGroup"
        },
        "vehiclesOwned": {
            "items": {
                "enum": [
                    "bicycle",
                    "car",
                    "motorbike",
                    "pedelec",
                    "public"
                ],
                "type": "string"
            },
            "type": "array"
        },
        "zipcode": {
            "type": "string"
        }
    },
    "type": "object"
}

=== FixMyBerlin/fixmy.frontend/src/pages/KatasterKI/scheme/sample-instances/profile-request-sample-instance.json
{
  "ageGroup": 1,
  "berlinTraffic": "3",
  "bicycleAccident": 1,
  "bicycleUse": 0,
  "bikeReasons": ["1", "5", "3"],
  "district": "Mitte",
  "gender": "d",
  "hasChildren": true,
  "isAgbAccepted": true,
  "transportRatings": {
    "pedelec": 0,
    "bicycle": 5,
    "motorbike": 3,
    "car": 0,
    "public": 3
  },
  "userGroup": "pedestrian",
  "vehiclesOwned": ["car"],
  "zipcode": "22000"
}

=== FixMyBerlin/fixmy.frontend/src/pages/KatasterKI/scheme/profile-request-sample-instance.json
{
    "ageGroup": 1,
    "berlinTraffic": "CCCC",
    "bicycleAccident": 1,
    "bicycleUse": 0,
    "bikeReasons": [
        "DD"
    ],
    "district": "aaaaa",
    "gender": "d",
    "hasChildren": true,
    "isAgbAccepted": true,
    "transportRatings": {
        "": 1
    },
    "userGroup": "pedestrian",
    "vehiclesOwned": [
        "car"
    ],
    "zipcode": "BBBB"
}
